---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: service-now-nginx-demo
spec:
  tower_auth_secret: toweraccess
  job_template_name: Demo Job Template
  extra_vars:
    sn_severity: 3
    sn_priority: 3
    appName: nginx-demonstration
