apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ansible-post-hook-placementrule
  namespace: ansiblepost
  labels:
    app: ansible
  annotations:
    apps.open-cluster-management.io/github-path: ansiblepost/resources
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: ansiblepost/git
  hooksecretref:
    name: srt
    namespace: ansiblepost
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-placementrule
      namespace: ansiblepost
