---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: posthook-test
  namespace: ansible
spec:
  job_template_name: Demo Job Template
  tower_auth_secret: toweraccess
  extra_vars:
    appName: nginx-demonstration
    sn_priority: 3
    sn_severity: 3

