apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: helmexample
  namespace: helmexample 
spec:
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - helmexample
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
